<?php

namespace App\Constants;

class FileFolders
{
    const USER_COVER_IMAGE = 'USER_COVER_IMAGE';

    const USER_PROFILE_IMAGE = 'USER_PROFILE_IMAGE';

    const CANDIDATE_PASSPORT_SIZE_IMAGE = 'CANDIDATE_PASSPORT_SIZE_IMAGE';

    const CANDIDATE_LARGE_IMAGE = 'CANDIDATE_LARGE_IMAGE';

    const SUBSCRIPTION_PLAN_IMAGE = 'SUBSCRIPTION_PLAN_IMAGE';

    const SUBSCRIPTION_ATTACHMENT = 'SUBSCRIPTION_ATTACHMENT';

    const SERVICE_IMAGE = 'SERVICE_IMAGE';
}
